app = "lalit-enrichment-api"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8000
  force_https = true

[processes]
  web = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[[vm]]
  size = "shared-cpu-1x"
